name: smart_receipt_scanner
description: "Smart Receipt Scanner - AI-powered OCR receipt scanning app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  image: ^4.5.0
  google_mlkit_text_recognition: ^0.14.0
  path_provider: ^2.1.5
  flutter_dotenv: ^6.0.1
  mongo_dart: ^0.10.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/models/datasets/images/
    - .env